apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jackieni-io-tls
spec:
  secretName: jackieni-io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: jackieni.io
  dnsNames:
    - jackieni.io
    - www.jackieni.io
